# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_add_result_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillvideo',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
