# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_add_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillvideo',
            name='annotated_video',
            field=models.FileField(blank=True, null=True, upload_to='annotated/'),
        ),
    ]
